apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: teastore-webui-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-webui
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: teastore_webui_cpu_usage_seconds
      target:
        type: AverageValue
        averageValue: "900m"
