apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-metrics-config
  namespace: monitoring
data:
  config.yaml: |
    rules:
      custom:
      - seriesQuery: 'container_cpu_usage_seconds_total{namespace="default",container!="",container!="POD"}'
        resources:
          overrides:
            namespace: {resource: "namespace"}
            pod: {resource: "pod"}
        name:
          as: "teastore_webui_cpu_usage_seconds_test"
        metricsQuery: 'avg(sum(rate(<<.Series>>{<<.LabelMatchers>>, container!="POD"}[2m])) by (pod))'

 