prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'nginx-ingress'
        metrics_path: '/metrics'
        scrape_interval: '5s'
        static_configs:
          - targets:
            - '10.0.95.15:10254'
